# Generated by Django 3.1.6 on 2021-02-03 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210203_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='api.wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
    ]
